### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by ninjaguppy** [goshatch/orgroam_to_obsidian#7]
I'm trying to get this script to work on MacOS and running into some issues. I made sure to install of the dependencies from the Gemfile and was hoping that the script would work without any changes (I don't know much about Ruby or coding in general--hence wanting to switch to Obsidian).

When I run the script this is the output:

> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/ostruct.rb:95:in 'block in initialize': undefined method 'to_sym' for 0:Integer (NoMethodError)
Did you mean?  to_s
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/ostruct.rb:94:in 'each_pair'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/ostruct.rb:94:in 'initialize'
	from ./convert.rb:15:in 'new'
	from ./convert.rb:15:in 'initialize'
	from ./convert.rb:60:in 'new'
	from ./convert.rb:60:in 'block in initialize'
	from ./convert.rb:59:in 'each'
	from ./convert.rb:59:in 'initialize'
	from ./convert.rb:99:in 'new'
	from ./convert.rb:99:in '\<main\>'

I'm not sure what the issues is---can you help at all?

**Comment by goshatch** [comment]
Hi — thanks for opening the issue! From the output, it seems like there is a problem parsing your org-roam database into data that this script can use. I've just pushed a change to the script that might help with this, please update your local version and give it another go.

**Comment by ninjaguppy** [comment]
Thanks so much for the fast response! I still get an error but now it is

> ❯ ./convert.rb
/Users/lucaskerbs/.gem/ruby/2.6.0/gems/pandoc-ruby-2.1.10/lib/pandoc-ruby.rb:307:in `execute': pandoc: input/roam/: openBinaryFile: inappropriate type (is a directory) (RuntimeError)
	from /Users/lucaskerbs/.gem/ruby/2.6.0/gems/pandoc-ruby-2.1.10/lib/pandoc-ruby.rb:276:in 'execute_pandoc'
	from /Users/lucaskerbs/.gem/ruby/2.6.0/gems/pandoc-ruby-2.1.10/lib/pandoc-ruby.rb:270:in 'convert_string'
	from /Users/lucaskerbs/.gem/ruby/2.6.0/gems/pandoc-ruby-2.1.10/lib/pandoc-ruby.rb:206:in 'convert'
	from /Users/lucaskerbs/.gem/ruby/2.6.0/gems/pandoc-ruby-2.1.10/lib/pandoc-ruby.rb:242:in 'block (2 levels) in <class:PandocRuby>'
	from ./convert.rb:38:in 'input_file_to_md'
	from ./convert.rb:16:in 'initialize'
	from ./convert.rb:61:in 'new'
	from ./convert.rb:61:in 'block in initialize'
	from ./convert.rb:60:in 'each'
	from ./convert.rb:60:in 'initialize'
	from ./convert.rb:100:in 'new'
	from ./convert.rb:100:in '\<main\>'

**Comment by CD11b** [comment]
Reverting this change removed errors for me on Ubuntu WSL

**Comment by goshatch** [comment]
Hi folks, I apologise for being very late looking at these issues. I made a note for myself to look at them in detail when I'm back from the holidays (around Jan. 5), and I'll provide a fix where I can.

Thank you for your patience!

**Comment by goshatch** [comment]
Hello! I've just pushed a new commit that adds some debugging code to the script.

Could you please pull the latest version, and give a try to running the script with the debug flag, like this:

```sh
$ ./convert.rb --debug
```

This should print some useful information that should help us resolve the issues that are happening here.

Thanks again for your patience!

**Comment by goshatch** [comment]
I'm going to close this for now, please feel free to reopen if still relevant.
